name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
 
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
 
    - name: Restore
      run: dotnet restore '/src/**/*.csproj'
 
    - name: Build
      run: dotnet build '/src/**/*.csproj' --configuration Release --no-restore
 
    - name: Test
      run: dotnet test '/src/**/*.csproj' --no-restore

    - name: Pack
      run: dotnet pack '/src/**/*.csproj' --configuration Release --no-build
 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet Package
        path: '**/*.nupkg'
